### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by LUS24** [fmassonn/sipn-south-public#4]
Hello, thanks for the great work!
I just wanted to report that the link ([http://acecrc.org.au/sipn-south/](http://acecrc.org.au/sipn-south/))  in the readme to the publication "Assessment of February 2018-2019 sea-ice forecasts for the Southern Ocean" doesn't redirect to that resource.

Kind regards,

Leo

**Comment by willrhobbs** [comment]
@LUS24 Thanks for alerting us to this, you're correct that ACE CRC  no longer exists. The correct link is 
https://eprints.utas.edu.au/29984/
